# -*- coding: utf-8 -*-
"""DN3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bBOnEmyd9-4aYGMD2dK6zqQqOuqlPLTV
"""

import pandas as pd
df1=pd.read_csv('AusOpen-men-2013.csv')
df2=pd.read_csv('AusOpen-women-2013.csv')
df3=pd.read_csv('FrenchOpen-men-2013.csv')
df4=pd.read_csv('FrenchOpen-women-2013.csv')
df5=pd.read_csv('USOpen-men-2013.csv')
df6=pd.read_csv('USOpen-women-2013.csv')
df7=pd.read_csv('Wimbledon-men-2013.csv')
df8=pd.read_csv('Wimbledon-women-2013.csv')
df7

"""total no. of unique players in all tournament plot the pie chart of distribution of unique players in each tournament in men category

"""

import pandas as pd
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")

df = pd.concat([df1, df2, df3, df4])
uni_players = len(df["Player1"].append(df["Player2"]).unique())


aus=len(df1["Player1"].append(df1["Player2"]).unique())
french=len(df2["Player1"].append(df2["Player2"]).unique())
us=len(df3["Player1"].append(df3["Player2"]).unique())
wimb=len(df4["Player1"].append(df4["Player2"]).unique())

print(uni_players)
print("unique players in aus:",aus,"french:",french,"us:",us,"wimb:",wimb)

labels = ['Aus', 'French', 'US','Wimbledon']
sizes = [aus, french, us, wimb]
plt.pie(sizes, labels=labels, autopct='%1.1f%%', startangle=90)
plt.title("Distribution of Unique Players in Each Tournament")
plt.show()

"""top 10 women players who played highest number of matches in australia
 and plot the bar graph

"""

import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv('AusOpen-women-2013.csv')

m=df.groupby('Player1').count()['Round']
top10=m.sort_values(ascending=False).head(10)
plt.bar(top10.index, top10.values)
plt.xticks(rotation=90)
plt.xlabel('Player')
plt.ylabel('Number of matches played')
plt.title('Top 10 women players  played most number of matches at Australian Open 2013')
plt.show()

"""
if Player 1 has won 50% or more of their net points attempted in a match in Frenchopen tournament, what is the probability that they will win the match?"""

import pandas as pd
df3=pd.read_csv('FrenchOpen-men-2013.csv')
df=df3[df3['NPA.1']/df3['NPW.1'] >= 0.50]
wins=len(df[df['Result']==1])

p=wins/len(df)
print(wins)
print(len(df))
print(p)

"""Plot a pie chart for the distribution of wins and losses of player 2 has a first serve won percentage of less than 50%?"""

import pandas as pd
import matplotlib.pyplot as plt

df4=pd.read_csv('FrenchOpen-women-2013.csv')

df=df4[df4['FSW.2']/df4['FSP.2']<0.5]
p=df.groupby('Result').size()
plt.pie(p,labels=['Lost','Won'], autopct='%1.1f%%')
plt.title('Matches with First Serve Won by Player 2 < 50%')
plt.show()

"""name the top 3 players who won most no. of matches in US tournament in men category

"""

import pandas as pd
df = pd.read_csv('USOpen-men-2013.csv')
c={}
for index, row in df.iterrows():
    player1 = row['Player1']
    player2 = row['Player2']
    result = row['Result']
    if result == 1:
        c[player1]=c.get(player1, 0) + 1
    else:
        c[player2] =c.get(player2, 0) + 1
top3=sorted(c.items(), key=lambda x: x[1], reverse=True)[:3]
for player, wins in top3:
    print(player, ":", wins)

"""plot a scatter plot of first serve percentage vs. second serve percentage for  player1 in US women tournament"""

import pandas as pd
import matplotlib.pyplot as plt

df3=pd.read_csv('USOpen-women-2013.csv')
plt.scatter(df3['FSP.1'], df3['SSP.1'])
plt.title('First Serve Percentage vs. Second Serve Percentage for Player1 in US women Tournament')
plt.xlabel('First Serve Percentage')
plt.ylabel('Second Serve Percentage')
plt.show()

"""What is the probability of player1 has higher percentage of break points than player 2 and given that player 1 won the match in wimbledon men tournament"""

import pandas as pd

df7=pd.read_csv('Wimbledon-men-2013.csv')

p1_win= len(df[df['Result'] == 1])
sample=len(df7[(df7['Result'] == 1) & (df7['BPW.1']>df7['BPW.2'])])
p=sample/p1_win
print(sample)
print(p1_win)
print(p)

"""plot a scatter plot between first serve percentage of player1 and result of that match."""

import matplotlib.pyplot as plt

plt.scatter(df1['FSP.1'], df1['Result'])
plt.xlabel('First Serve Percentage for Player 1')
plt.ylabel('Result of the Match')
plt.title('Scatter Plot: First Serve Percentage vs. Match Result')
plt.show()